name: vipy unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.7, 3.10]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names	
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=300 --ignore=E231,E722,W504,W503,F841,E702,E731,F821,F401,W605,F824
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=300 --statistics --ignore=E231,E722,W504,W503,F841,E702,E731,F821,F401,W605,F824
    - name: Test with pytest
      run: |
        pip install pytest
        PYTHONPATH=. pytest
